### register user
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "kkiki6001@gmail.com",
    "password": "123456",
    "name" : "kiki",
    "phone" : "010-1234-5678"
}

### login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "kkiki6001@gmail.com",
    "password": "123456"
}